# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
minimum_pre_commit_version: '2.9.0'
default_language_version:
    python: python3
exclude: 'tests/data/.*|src/pymodulon/data/.*|.bumpversion.cfg'

ci:
  skip: [no-commit-to-branch]

repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.0.1
      hooks:
      - id: check-added-large-files
        args: ['--maxkb=100000']
      - id: check-json
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: no-commit-to-branch
    - repo: https://github.com/pre-commit/pygrep-hooks
      rev: v1.9.0
      hooks:
      - id: python-check-blanket-noqa
      - id: python-no-eval
      - id: python-no-log-warn
      - id: python-use-type-annotations
      - id: rst-backticks
      - id: rst-directive-colons
      - id: rst-inline-touching-normal
    - repo: https://github.com/pycqa/isort
      rev: 5.9.1
      hooks:
      - id: isort
    - repo: https://github.com/psf/black
      rev: 21.6b0
      hooks:
      - id: black
    - repo: https://github.com/asottile/blacken-docs
      rev: v1.10.0
      hooks:
      - id: blacken-docs
        additional_dependencies: [black==20.8b1]
    - repo: https://github.com/PyCQA/flake8
      rev: 3.9.2
      hooks:
      - id: flake8
